M48
; DRILL file {KiCad 9.0.3+dfsg-1} date 2026-03-15T14:09:02+0100
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2026-03-15T14:09:02+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.3+dfsg-1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X3.3366Y-2.9035
X3.3465Y-2.5591
X5.5118Y-2.5591
X5.5217Y-2.9035
M30
